### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by indrablake** [UCSD/wifi_connection#2]
<img width="405" alt="Screen Shot 2021-04-20 at 07 43 35" src="https://user-images.githubusercontent.com/30803436/115320538-50625300-a1ac-11eb-9134-d1b418e57969.png">

how to solve this?

**Comment by c3bryant** [comment]
Hi @indrablake,
If you would please include your `flutter doctor --verbose` output and the `wifi_connection` version you are using in your pubspec.

**Comment by indrablake** [comment]
hi @c3bryant 

this is my flutter verbose
[✓] Flutter (Channel master, 2.1.0-13.0.pre.175, on macOS 11.0.1 20B29 darwin-arm, locale en-ID)
    • Flutter version 2.1.0-13.0.pre.175 at /Users/samjin/Documents/development/flutter
    • Framework revision efbde443d2 (5 weeks ago), 2021-03-18 13:40:08 -0700
    • Engine revision c4628b709c
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/samjin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.5, Build version 12E5244e
    • CocoaPods version 1.10.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 504bb465313b6c1bdbe8766a5e726207d3cf5ee8 • ios • iOS 14.4.2

**Wifi_connection Plugin**
wifi_connection: ^0.0.3

**Comment by c3bryant** [comment]
@indrablake Thank you for sending this information. We believe the issue has been resolved in a new version available on pub.dev - [wifi_connection 0.0.4](https://pub.dev/packages/wifi_connection/versions/0.0.4).

If you run into further problems let me know.
